import { P2PMessage, PROTOCOL_VERSION } from '@/core/network/protocol';
import { DesignNode } from '../core/DesignNode';

export const UI_AI_TYPE_KEYS = {
  TASK_OFFER: 'ui-ai/task-offer',
  TASK_ACCEPT: 'ui-ai/task-accept',
  TASK_REJECT: 'ui-ai/task-reject',
  TASK_PROGRESS: 'ui-ai/task-progress',
  TASK_RESULT: 'ui-ai/task-result',
  TOOL_REQUEST: 'ui-ai/tool-request',
  TOOL_RESPONSE: 'ui-ai/tool-response',
} as const;

export type UiAiMessageType = typeof UI_AI_TYPE_KEYS[keyof typeof UI_AI_TYPE_KEYS];

export interface UiSubtask {
  id: string;
  rootTaskId: string;
  initiatorPeerId: string;
  title: string;
  description: string;
  nodeIds: string[]; // Target nodes for this subtask
  contextNodes: DesignNode[]; // JSON snapshot of target nodes for LLM
  allowedTools: string[];
  dependencies: string[];
  status: 'queued' | 'assigned' | 'in_progress' | 'completed' | 'failed' | 'cancelled';
  assignedPeerId?: string;
  leaseId?: string;
  resultPatch?: any; // The changes generated by the AI
}

export interface UiRootTask {
  id: string;
  prompt: string;
  ownerPeerId: string;
  status: 'planning' | 'running' | 'completed' | 'failed' | 'cancelled';
  subtaskIds: string[];
  createdAt: number;
}
